# sam doc: https://github.com/awslabs/serverless-application-model/blob/master/docs
# lambda doc: https://docs.aws.amazon.com/lambda/latest

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple_url_shortener

Globals:
  Function:
    Timeout: 3
    Runtime: go1.x
    Tracing: Active
    Environment:
      Variables:
        BASE_URL: https://kho21.com
        AWS_MY_REGION: ap-northeast-1
        DYNAMO_ENDPOINT: https://dynamodb.ap-northeast-1.amazonaws.com
        DYNAMO_TABLE: !Ref DynamoTable

Resources:
  DynamoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: prod_urls
      PrimaryKey:
        Name: shorten
        Type: String
      # wcu 50で200reqs/sまで耐える
      # wcu 100で500reqs/sまで耐える
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/lambda/shorten/
      Handler: shorten
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable
  RestoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/lambda/restore/
      Handler: restore
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{token}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  API:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  DynamoDB:
    Description: "dynamo db ARN"
    Value: !GetAtt DynamoTable.Arn

  ShortenFunction:
    Description: "shorten Lambda Function ARN"
    Value: !GetAtt ShortenFunction.Arn
  ShortenFunctionIamRole:
    Description: "Implicit IAM Role created for shorten function"
    Value: !GetAtt ShortenFunctionRole.Arn

  RestoreFunction:
    Description: "restore Lambda Function ARN"
    Value: !GetAtt RestoreFunction.Arn
  RestoreFunctionIamRole:
    Description: "Implicit IAM Role created for restore function"
    Value: !GetAtt RestoreFunction.Arn
