# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'pry-byebug'
gem 'rest-client'
gem 'rspec'
gem 'rubocop', '~> 0.71.0', require: false
