resources:
- name: sus
  type: s3
  check_every: 5s
  source:
    bucket: sus-ci
    region_name: ap-northeast-1
    access_key_id: ((ci_aws_access_key_id))
    secret_access_key: ((ci_aws_secret_access_key))
    versioned_file: sus.zip

jobs:
- name: job_build
  plan:
  - get: sus
    trigger: true
    params:
      unpack: true
  - task: unit_test
    file: sus/ci/task_unit_test.yml
  - task: deploy
    file: sus/ci/task_deploy.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci_aws_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((ci_aws_secret_access_key))

- name: job_integration_test
  plan:
  - get: sus
    trigger: true
    params:
      unpack: true
    passed: [job_build]
  - task: test
    file: sus/ci/task_integration_test.yml
    params:
      BASE_URL: https://kho21.com
