resources:
- name: sus
  type: s3
  source:
    bucket: sus-ci
    region_name: ap-northeast-1
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_access_token))
    versioned_file: sus.zip

jobs:
- name: test
  plan:
  - get: sus
    trigger: true
    params:
      unpack: true
  - task: unit_test
    file: sus/ci/task_unit_test.yml
