resources:
- name: sus
  type: s3
  source:
    bucket: sus-ci
    region_name: ap-northeast-1
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    versioned_file: sus.zip

jobs:
- name: job_unit_test
  plan:
  - get: sus
    trigger: true
    params:
      unpack: true
  - task: unit_test
    file: sus/ci/task_unit_test.yml

- name: job_deploy
  plan:
  - get: sus
    trigger: true
    params:
      unpack: true
    passed: [job_unit_test]
  - task: deploy
    file: sus/ci/task_deploy.yml
    params:
      AWS_ACCESS_KEY_ID: ((aws_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
